import Head from 'next/head'
import Button from '@/components/Button'
import Navbar from '@/components/Navbar'

export default function Home() {
    return (
        <>
            <Head>
                <title>Biblio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <body className='bg-gray-100 h-screen'>
                <Navbar/>

                <main>
                    <Button>ciao</Button>
                    
                </main>    
            </body>

        </>
    )
}
